AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: the leech pipeline for migrating information into the leech data system

Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  NeptuneSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A collection of Security Group IDs capable of interacting with the Neptune Cluster
  NeptuneSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: A collection of Subnet IDs which can interact with the Neptune Cluster
  WorkerRoleArn:
    Type: String
    Description: the ARN of the role to be used by the leech

Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Globals:
  Function:
    Runtime: python3.7
    Tracing: Active
    Environment:
      Variables:
        DEBUG: !Ref IsDev

Resources:
  LeechH:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.handler
      Role: !Ref WorkerRoleArn
      Timeout: 45
      CodeUri: src/
  VpcLeech:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.handler
      CodeUri: src/
      Role: !Ref WorkerRoleArn
      VpcConfig:
        SecurityGroupIds: !Ref NeptuneSecurityGroupIds
        SubnetIds: !Ref NeptuneSubnetIds
  StarterH:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.starter_handler
      Role: !Ref WorkerRoleArn
      Timeout: 120
      CodeUri: src/
