AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: the leech pipeline for migrating information into the leech data system

Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  DataGqlEndpoint:
    Type: String
    Description: the endpoint of the GQL API used to interface with the data layer
  EncounterBucketName:
    Type: String
    Description: the bucket used to hold documentation for encounters
  StorageBucketName:
    Type: String
    Description: the bucket used by the module for storage
  SensitivesTableName:
    Type: String
    Description: the table holding the PHI information
    Default: 'Sensitives'

Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Resources:
  Task:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.handler
      Role: !ImportValue dev-worker-role-arn
      Runtime: python3.7
      Tracing: Active
      Timeout: 900
      CodeUri: src/
      Environment:
        Variables:
          DEBUG: !Ref IsDev
          SENSITIVES_TABLE_NAME: !Ref SensitivesTableName
          GRAPH_GQL_ENDPOINT: !Ref DataGqlEndpoint
          STORAGE_BUCKET_NAME: !Ref StorageBucketName
          ENCOUNTER_BUCKET: !Ref EncounterBucketName
      Events:
        leech:
          Type: SQS
          Properties:
            Queue: !GetAtt Leech.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
        generateSourceVertex:
          Type: SQS
          Properties:
            Queue: !GetAtt GenerateSourceVertex.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
        derivePotentialConnections:
          Type: SQS
          Properties:
            Queue: !GetAtt DerivePotentialConnections.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
        checkForExistingVertexes:
          Type: SQS
          Properties:
            Queue: !GetAtt CheckForExistingVertexes.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
        generatePotentialEdge:
          Type: SQS
          Properties:
            Queue: !GetAtt GeneratePotentialEdge.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
  Leech:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion: 0.0.9
      Parameters:
        TaskName: 'leech'
  GenerateSourceVertex:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion:  0.0.9
      Parameters:
        TaskName: 'generate_source_vertex'
        DeadLetterArn: !GetAtt Leech.Outputs.DeadLetterArn
        MasterKeyId: !GetAtt Leech.Outputs.MasterKeyId
  DerivePotentialConnections:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion:  0.0.9
      Parameters:
        TaskName: 'derive_potential_connections'
        DeadLetterArn: !GetAtt Leech.Outputs.DeadLetterArn
        MasterKeyId: !GetAtt Leech.Outputs.MasterKeyId
  CheckForExistingVertexes:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion:  0.0.9
      Parameters:
        TaskName: 'check_for_existing_vertexes'
        DeadLetterArn: !GetAtt Leech.Outputs.DeadLetterArn
        MasterKeyId: !GetAtt Leech.Outputs.MasterKeyId
  GeneratePotentialEdge:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion: 0.0.9
      Parameters:
        TaskName: 'generate_potential_edge'
        DeadLetterArn: !GetAtt Leech.Outputs.DeadLetterArn
        MasterKeyId: !GetAtt Leech.Outputs.MasterKeyId

Outputs:
  LeechFunction:
    Description: "task function ARN"
    Value: !GetAtt Task.Arn
