AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: the leech pipeline for migrating information into the leech data system
Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  DevApiKey:
    Type: String
    Description: if dev mode is enabled, the API requires an API key instead of auth sig
    Default: ''
  DataGqlEndpoint:
    Type: String
    Description: the endpoint of the GQL API used to interface with the data layer
    Default: 'yiawofjaffgrvlzyg2f6xnjzty.appsync-api.us-east-1.amazonaws.com'
  LayerArn:
    Type: String
    Description: the lambda layer containing the common dependencies
    Default: 'arn:aws:lambda:us-east-1:726075243133:layer:algLayer:4'
  SensitivesTableName:
    Type: String
    Description: the table holding the PHI information
    Default: 'Sensitives'
Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']
Globals:
  Function:
    Runtime: python3.6
    Timeout: 300
    Tracing: Active
    Layers:
      - !Ref LayerArn
    Environment:
      Variables:
        DEBUG: !Ref IsDev
        GQL_APIK_KEY: !If [DevDeploy, !Ref DevApiKey, '']
        LEECH_LISTENER_ARN: !Ref Listener
        SENSITIVES_TABLE_NAME: !Ref SensitivesTableName
        GRAPH_GQL_ENDPOINT: !Ref DataGqlEndpoint
Resources:
  Task:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.tasks.leech.task
      Role: !ImportValue dev-worker-role-arn
      CodeUri: src/
      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt EventQueue.Arn
            BatchSize: 10
  Listener:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: leech-listener
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: !GetAtt EventQueue.Arn
          Protocol: sqs
  EventQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt DeadLetter.Arn
        maxReceiveCount: 50
      KmsMasterKeyId: !Ref MasterKey
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Id: "SqsPolicy"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "SQS:SendMessage"
            Resource: !GetAtt EventQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref Listener
      Queues:
        - !Ref EventQueue
  MasterKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: [
              !Sub "arn:aws:iam::${AWS::AccountId}:root",
              !Sub 'arn:aws:sts::${AWS::AccountId}:assumed-role/CodeStarWorker-leechdev-CloudFormation/AWSCloudFormation'
            Action:
              - "kms:*"
            Resource: "*"
          -
            Effect: "Allow"
            Principal:
              Service:
                - "sns.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "kms:GenerateDataKey*"
              - "kms:Decrypt"
            Resource: "*"
  DeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
      MessageRetentionPeriod: 1209600
Outputs:
  LeechFunction:
    Description: "task function ARN"
    Value: !GetAtt Task.Arn
  ListenerArn:
    Description: "the ARN endpoint for the task module"
    Value: !Ref Listener
    Export:
      Name: !Sub "${AWS::StackName}-leech-listener"