AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: the leech pipeline for migrating information into the leech data system

Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  DataGqlEndpoint:
    Type: String
    Description: the endpoint of the GQL API used to interface with the data layer
  EncounterBucketName:
    Type: String
    Description: the bucket used to hold documentation for encounters
  StorageBucketName:
    Type: String
    Description: the bucket used by the module for storage
  SensitivesTableName:
    Type: String
    Description: the table holding the PHI information
    Default: 'Sensitives'
  FireHoseName:
    Type: String
    Description: the Firehose stream used to push objects to S3

Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Globals:
  Function:
    Runtime: python3.7
    Tracing: Active
    Environment:
      Variables:
        DEBUG: !Ref IsDev
        SENSITIVES_TABLE_NAME: !Ref SensitivesTableName
        STORAGE_BUCKET_NAME: !Ref StorageBucketName
        ENCOUNTER_BUCKET: !Ref EncounterBucketName
        FIRE_HOSE_NAME: !Ref FireHoseName

Resources:
  LeechH:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.handler
      Role: !ImportValue dev-worker-role-arn
      Timeout: 45
      CodeUri: src/
  StarterH:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.starter_handler
      Role: !ImportValue dev-worker-role-arn
      Timeout: 120
      CodeUri: src/
