AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: the leech pipeline for migrating information into the leech data system

Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  DataGqlEndpoint:
    Type: String
    Description: the endpoint of the GQL API used to interface with the data layer
  EncounterBucketName:
    Type: String
    Description: the bucket used to hold documentation for encounters
  StorageBucketName:
    Type: String
    Description: the bucket used by the module for storage
  SensitivesTableName:
    Type: String
    Description: the table holding the PHI information
    Default: 'Sensitives'
  FireHoseName:
    Type: String
    Description: the Firehose stream used to push objects to S3

Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Globals:
  Function:
    Runtime: python3.7
    Tracing: Active
    Environment:
      Variables:
        DEBUG: !Ref IsDev
        SENSITIVES_TABLE_NAME: !Ref SensitivesTableName
        STORAGE_BUCKET_NAME: !Ref StorageBucketName
        ENCOUNTER_BUCKET: !Ref EncounterBucketName
        FIRE_HOSE_NAME: !Ref FireHoseName

Resources:
  AioH:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.aio_handler
      Role: !ImportValue dev-worker-role-arn
      Timeout: 45
      CodeUri: src/
      Events:
        aio:
          Type: SQS
          Properties:
            Queue: !GetAtt Aio.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
  FireHoseH:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.fire_hose_handler
      Role: !ImportValue dev-worker-role-arn
      Timeout: 45
      CodeUri: src/
      Events:
        firehose:
          Type: SQS
          Properties:
            Queue: !GetAtt FireHose.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
  StarterH:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.starter_handler
      Role: !ImportValue dev-worker-role-arn
      Timeout: 120
      CodeUri: src/
  FireHose:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion: 0.0.9
      Parameters:
        TaskName: 'firehose'
  Aio:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion: 0.0.9
      Parameters:
        TaskName: 'aio'
