AWSTemplateFormatVersion: 2010-09-09
Transform:
  - 'AWS::Serverless-2016-10-31'
Parameters:
  SensitivesTableName:
    Type: String
    Description: name to be assigned to table which hold PHI
    Default: Sensitives
  IndexTableName:
    Type: String
    Description: name to be assigned to the table which will hold the indexes
    Default: Indexes
  MigrationTableName:
    Type: String
    Description: the name to associate with the migration table
    Default: Migration
Resources:
  SensitivesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref SensitivesTableName
      AttributeDefinitions:
        - AttributeName: insensitive
          AttributeType: S
      KeySchema:
        - AttributeName: insensitive
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
  MigrationTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref MigrationTableName
      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S
        - AttributeName: id_value
          AttributeType: N
      KeySchema:
        - AttributeName: identifier
          KeyType: HASH
        - AttributeName: id_value
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
  IndexTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref IndexTableName
      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S
        - AttributeName: sid_value
          AttributeType: S
        - AttributeName: internal_id
          AttributeType: S
        - AttributeName: numeric_id_value
          AttributeType: N
      KeySchema:
        - AttributeName: identifier
          KeyType: HASH
        - AttributeName: sid_value
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: internal_id_index
          KeySchema:
            - AttributeName: internal_id
              KeyType: HASH
            - AttributeName: identifier
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: identifier_index
          KeySchema:
            - AttributeName: identifier
              KeyType: HASH
            - AttributeName: numeric_id_value
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
Outputs:
  SensitivesTableName:
    Description: the name of the generated table used to house PHI
    Value: !Ref SensitivesTableName
  IndexTableName:
    Description: the name of the generated table to be used for indexing
    Value: !Ref IndexTableName
  MigrationTableName:
    Description: the name of the generated table to be used to track object migration
    Value: !Ref MigrationTableName
